version: '3'
#docker stack
services:

  mongodb:
    image: 'bitnami/mongodb:3.7.5-r0'
    restart: always
    environment:
      - MONGODB_DATABASE=db
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=123
      - MONGODB_ADVERTISED_HOSTNAME=192.168.200.212
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'

  redis:
    image: 'bitnami/redis:4.0.14-debian-9-r118'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis/data'
    
  redis-sentinel:
    image: 'bitnami/redis-sentinel:4.0.14-debian-9-r114'
    restart: always
    ports:
      - "26379:26379"
    environment:
      - REDIS_MASTER_HOST=192.168.200.212
    volumes:
    #权限FIX
    #mkdir /data/commonDevSet
    #mkdir /data/commonDevSet/redis_sentinel_data
    #chmod 777 /data/commonDevSet/redis_sentinel_data
    #移除重建后还会有目录问题
      - '/data/commonDevSet/redis_sentinel_data:/bitnami'

  rabbitmq:
    image: 'bitnami/rabbitmq:3.7.17'
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/bitnami'

  consul-server-bootstrap:
    image: consul:1.2.1
    ports:
      - 8500:8500
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0 -bind '{{ GetInterfaceIP \"eth0\" }}'"

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local