#TODO app修改为对应的内容
server:
  port: 8080
  context-path: /app

spring:
  application:
    name: app
  profiles:
    active: dev

app:
  name: springWeb
  jwt:
    secret: 123abc
    #一天
    expirationTime: 86400000

---

spring:
  profiles: dev

---

spring:
  profiles: test

---

spring:
  profiles: prod